name: Test build docs

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test docs deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Setup Python environment
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.x"
      # - name: Install Python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install --upgrade sphinx sphinx-markdown-builder
      # - name: Build ACA-Py markdown
      #   run: sphinx-build -b markdown -a -E -c ./ ./ ./build
      #   working-directory: docs/rtd/
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./
      - name: Test build doc site
        run: yarn build
        working-directory: ./